<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0-windows;net47;net48</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <LangVersion>10.0</LangVersion>
    <Title>WpfSeasonalAnimations</Title>
    <Authors>nafrolov</Authors>
    <Description>Customizable WPF controls with animation for each season</Description>
    <Copyright>Copyright (c) 2026 nafrolov</Copyright>
    <PackageProjectUrl>https://github.com/nafrolov/WpfSeasonalAnimations</PackageProjectUrl>
    <PackageReadmeFile>README.nuget.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/nafrolov/WpfSeasonalAnimations</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>seasons,snow,snowfall,wpf,snowflake,winter,leaf,leaffall,autumn</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReleaseNotes>Full snowfall and leaf fall controls support</PackageReleaseNotes>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Art\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
